name: Release Semantic Version by Conventional Commits
description: Creates a release and tag based on conventional commits on GitHub
branding:
  icon: tag
  color: black
author: fdiesel
runs:
  using: node20
  main: dist/index.js
  post: dist/post.js
inputs:
  token:
    description: The github token. Use secrets.GITHUB_TOKEN
    required: true
  phase:
    description: The phase of the release (dev / prod)
    default: dev
    required: true
  app_name:
    description: The name of the app to link to in the discord release
    required: false
  app_url:
    description: The URL of the app to link to in the discord release
    required: false
  discord_webhooks:
    description: The discord webhook to send releases to
    required: false
  discord_release_color:
    description: The color of the discord release
    required: false
  _job_status:
    description: DO NOT TOUCH
    default: ${{ job.status }}
outputs:
  created:
    description: If a release was created
  preRelease:
    description: Pre-release type if the release is a pre-release
  tag:
    description: Tag name
  majorTag:
    description: Major tag name
  version:
    description: Semantic version
  majorVersion:
    description: Major version
