name: CI

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PHASE: prod

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Clean Build
        run: rm -rf node_modules dist

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          git add -f node_modules dist
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "chore: update dist"
            git push origin HEAD
          fi

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        id: release
        uses: fdiesel/release-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          phase: prod

      - name: Update Version in Files
        run: |
          npm version ${{ steps.release.outputs.version }} --allow-same-version --no-git-tag-version
          sed -i "s/release-action@v[0-9]\+/release-action@v${{ steps.release.outputs.majorTag }}/g" README.md
          git add README.md
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "chore: update version files"
            git push origin HEAD
          fi
